---
title: "Step14-LongVsShortStays"
author: "Karina Wallrafen-Sam"
date: "4/4/2022"
output: html_document
---

```{r}
longTermIDs <- durations[durations$startCensored == "Y" & 
                           durations$endCensored == "Y", "id"]
longTermIDs <- longTermIDs[!duplicated(longTermIDs)]

shortTermIDs <- durations[durations$startCensored == "N" & 
                            durations$endCensored == "N", "id"]
shortTermIDs <- shortTermIDs[!duplicated(shortTermIDs)]

ids_full <- cDailyLoc_full %>% group_by(id) %>%
  summarise(DaysOfData = n(), FirstDate = min(Date), LastDate = max(Date),
            NumLocs = n_distinct(Location), InitialAge = last(InitialAge),
            Gender = first(Gender), Race = last(Race))

ids_full$type <- NA
ids_full[ids_full$id %in% longTermIDs, ]$type <- "Long-Term"
ids_full[ids_full$id %in% shortTermIDs, ]$type <- "Short-Term"

remove(longTermIDs, shortTermIDs)

ids2 <- ids_full
ids2[ids2$Race != "White" & ids2$Race != "Black", ]$Race <- "Other"
ids2$InitialAge <- cut(ids2$InitialAge, breaks=c(0, 20, 30, 40, 50, 60, 100), 
                       right = FALSE, labels = c("Under 20", "20 - 29", 
                                                 "30 - 39", "40 - 49", 
                                                 "50 - 59", "60+"))

types1 <- ids2 %>% group_by(type) %>% summarise(category = "Overall", 
                                               numPeople = n())
types2 <- ids2 %>% group_by(Race, type) %>% 
  summarise(numPeople = n(), .groups = "drop_last")
names(types2)[names(types2) == 'Race'] <- 'category'
types2$category <- paste("Race", types2$category)
types3 <- ids2 %>% group_by(InitialAge, type) %>% 
  summarise(numPeople = n(), .groups = "drop_last")
names(types3)[names(types3) == 'InitialAge'] <- 'category'
types3$category <- paste("Age", types3$category)

typesSummary <- rbind(types1, types2, types3)
remove(types1, types2, types3, ids2)

cDailyLoc_full$Floor <- substr(cDailyLoc_full$Location, 0, 1)
for (i in seq_along(allFloors)){
  currentFloor <- cDailyLoc_full[cDailyLoc_full$Floor == allFloors[i], c("id")]
  currentFloor <- currentFloor[!duplicated(currentFloor), ]
  currentFloor <- merge(currentFloor, ids_full[ , c("id", "type")], by = "id")
 
  currentFloorTypes <- currentFloor %>% group_by(type) %>% 
    summarise(category = paste("Floor", allFloors[i]), numPeople = n())
  
  typesSummary <- rbind(typesSummary, currentFloorTypes)
}
remove(currentFloor, currentFloorTypes, i)

typesSummary <- typesSummary %>% group_by(category) %>%
  mutate(percentPeople = round(numPeople / sum(numPeople), 4) * 100) 
typesSummary <- typesSummary[,c(2,1,3,4)]
typesSummary <- typesSummary[complete.cases(typesSummary), ]

print(knitr::kable(typesSummary[c(1:2, 21:nrow(typesSummary)), ], 
                   caption = "# of long-term vs. short-term residents 
                     (overall and by floor)"))

#Estimate average active spell duration for long vs short term
durations <- merge(durations, ids_full[ , c("id", "type")], by = "id")
meanDurLT <- mean(durations[durations$type %in% c("Long-Term"), ]$duration)
meanDurST <- mean(durations[durations$type %in% c("Short-Term"), ]$duration)
```  

##### The mean active spell duration for long-term residents is `r meanDurLT` days (by definition).

##### The mean active spell duration for short-term residents is `r meanDurST` days.

```{r}  
#Estimate average duration of cell location spell for long vs short term
cLocs_full <- merge(cLocs_full, ids_full[ , c("id", "type")], 
                      by = "id")

cLocDurations2 <- cLocs_full %>% 
  group_by(startCensored, endCensored, type) %>% 
  summarise(meanDur = mean(duration), numSpells = n(), 
            .groups = "drop_last")
names(cLocDurations2)[names(cLocDurations2) == 'type'] <- 'category'
cLocDurations2$category <- cLocDurations2$category %>% replace_na('Neither')

cLocDurations2 <- cLocDurations2[with(cLocDurations2, order(category)), ]
cLocDurations2 <- cLocDurations2 %>% group_by(category) %>%
  mutate(percentSpells = numSpells / sum(numSpells)) 
print(knitr::kable(cLocDurations2, 
                   caption = "Mean duration of cell-level location spells 
                     for long- vs. short-term residents"))

#Estimate average duration of block location spell for long vs short term
bLocs_full <- merge(bLocs_full, ids_full[ , c("id", "type")], 
                      by = "id")

bLocDurations2 <- bLocs_full %>% 
  group_by(startCensored, endCensored, type) %>% 
  summarise(meanDur = mean(duration), numSpells = n(), 
            .groups = "drop_last")
names(bLocDurations2)[names(bLocDurations2) == 'type'] <- 'category'
bLocDurations2$category <- bLocDurations2$category %>% replace_na('Neither')


bLocDurations2 <- bLocDurations2[with(bLocDurations2, order(category)), ]
bLocDurations2 <- bLocDurations2 %>% group_by(category) %>%
  mutate(percentSpells = numSpells / sum(numSpells)) 
print(knitr::kable(bLocDurations2, 
                   caption = "Mean duration of block-level location spells 
                     for long- vs. short-term residents"))
```
