---
title: "Step8-CellDegreeDistByAttr"
author: "Karina Wallrafen-Sam"
date: "4/1/2022"
output: html_document
---

```{r}
library(gridExtra)

#Degree distribution by attribute: floor, age, race
for (i in seq_len(nrow(dates))){
  currNW <- as.network(network.extract(cDynNW, at = dates$DayNum[i]))
  currNodes <- data.frame(id = get.vertex.attribute(currNW, "vertex.names"),
                          race = get.vertex.attribute(currNW, "Race"),
                          age = get.vertex.attribute(currNW, "Age"),
                          floor = get.vertex.attribute.active(currNW, "location",
                                                        at = dates$DayNum[i]),
                          degree = get_degree(currNW))
  currNodes$floor <- substr(currNodes$floor, 0, 1)
  currNodes$age <- cut(currNodes$age, breaks=c(0, 20, 30, 40, 50, 60, 100), 
                       right = FALSE, labels = c("Under 20", "20 - 29", 
                                                 "30 - 39", "40 - 49", 
                                                 "50 - 59", "60+"))
  currNodes[currNodes$race != "White" & currNodes$race != "Black", ]$race <- 
    "Other"

  dist_f <- currNodes %>% group_by(floor, degree) %>% 
    summarise(count = n(), .groups = "drop_last")
  dist_r <- currNodes %>% group_by(race, degree) %>% 
    summarise(count = n(), .groups = "drop_last")
  dist_a <- currNodes %>% group_by(age, degree) %>% 
    summarise(count = n(), .groups = "drop_last")

  names(dist_f)[names(dist_f) == "count"] <- toString(dates$Date[i])
  names(dist_r)[names(dist_r) == "count"] <- toString(dates$Date[i])
  names(dist_a)[names(dist_a) == "count"] <- toString(dates$Date[i])

  if (i == 1){
    cDegDists_floor <- dist_f
    cDegDists_race <- dist_r
    cDegDists_age <- dist_a
  } else {
    cDegDists_floor <- merge(cDegDists_floor, dist_f, by = c("floor", "degree"),
                             all = TRUE)
    cDegDists_race <- merge(cDegDists_race, dist_r, by = c("race", "degree"),
                            all = TRUE)
    cDegDists_age <- merge(cDegDists_age, dist_a, by = c("age", "degree"),
                           all = TRUE)
  }
}
remove(dist_f, dist_r, dist_a, currNW, currNodes)
```

#### Degree Distributions for Selected Floors & Time Points

```{r} 
#Histograms of degree distribution by floor:
par(mfrow = c(3,2))
floors <- c(2, 7)
for (j in seq_along(floors)) {
  for (i in seq_along(days)) {
    barplot(cDegDists_floor[cDegDists_floor$floor == floors[j], ][, (days[i] + 2)],
        names.arg = cDegDists_floor[cDegDists_floor$floor == floors[j], ]$degree,
        xlab = "Degree", ylab = "Frequency",
        main = paste("Degree Dist. on", dates$Date[days[i]], "on Floor",
                     floors[j], sep=" "))
  }
}
```

#### Degree Distributions for Selected Races & Time Points

```{r}
#Histograms of degree distribution by race:
par(mfrow = c(3,2))
races <- c("Black", "White")
for (j in seq_along(races)) {
  for (i in seq_along(days)) {
    barplot(cDegDists_race[cDegDists_race$race == races[j], ][, (days[i] + 2)],
        names.arg = cDegDists_race[cDegDists_race$race == races[j], ]$degree,
        xlab = "Degree", ylab = "Frequency",
        main = paste("Degree Dist. on", dates$Date[days[i]], "for",
                     races[j], "Residents", sep=" "))
  }
}
```

#### Degree Distributions for Selected Age Groups & Time Points

```{r}
#Histograms of degree distribution by age:
par(mfrow = c(3,2))
ages <- c("20 - 29", "40 - 49")
for (j in seq_along(ages)) {
  for (i in seq_along(days)) {
    barplot(cDegDists_age[cDegDists_age$age == ages[j], ][, (days[i] + 2)],
        names.arg = cDegDists_age[cDegDists_age$age == ages[j], ]$degree,
        xlab = "Degree", ylab = "Frequency",
        main = paste("Degree Dist. on", dates$Date[days[i]],
                     "for", ages[j], "Yr. Olds", sep=" "))
  }
}
```

#### Mean Degree over Time by Floor

```{r}
#Mean degree by floor at each time point
cDegDists_floor2 <- gather(cDegDists_floor, key = "Date", value = "Number", 
                          -floor, -degree)
cDegDists_floor2$Date <- as.Date(cDegDists_floor2$Date)
cDegDists_floor2 <- cDegDists_floor2[complete.cases(cDegDists_floor2), ]
cMeanDeg_floor <- cDegDists_floor2 %>% group_by(floor, Date) %>% 
  summarise(cMeanDeg = weighted.mean(degree, Number), 
            sd = SD(degree, weights = Number), min = min(degree), 
            max = max(degree), .groups = "drop_last")
par(mfrow = c(2,2))
floors <- 1:7
max.y <- ceiling(max(cMeanDeg_floor$cMeanDeg) * 10) / 10
min.y <- floor(min(cMeanDeg_floor$cMeanDeg) * 10) / 10
for (i in seq_along(floors)) {
    plot(cMeanDeg_floor[cMeanDeg_floor$floor == floors[i], ]$Date, 
         y = cMeanDeg_floor[cMeanDeg_floor$floor == floors[i], ]$cMeanDeg,
         xlab = "Date", ylab = "Mean Degree", 
         main = paste("Mean degree over time for floor", floors[i], sep=" "),
         ylim = c(min.y, max.y))
}
plot.new()
max.y <- max(cMeanDeg_floor$max)
for (i in seq_along(floors)){
  temp <- cMeanDeg_floor[cMeanDeg_floor$floor == floors[i], ]
  g <- (ggplot(temp,aes(x=Date)) + 
    geom_boxplot(aes(lower=(cMeanDeg-sd), upper=(cMeanDeg+sd), middle=cMeanDeg, 
                     ymin=min, ymax=max, group = Date), stat="identity") + 
    ggtitle(paste("Mean degree over time for floor", floors[i], sep=" ")) + 
    xlab("Date") + ylab("Degree") + ylim(NA, max.y))
  assign(paste0("f", i), g)
}
grid.arrange(f1, f2, f3, f4, ncol = 2)
grid.arrange(f5, f6, f7, ncol = 2)
remove(cDegDists_floor2, temp, f1, f2, f3, f4, f5, f6, f7)
```

#### Mean Degree over Time by Race

```{r}
#Mean degree by race at each time point
cDegDists_race2 <- gather(cDegDists_race, key = "Date", value = "Number", 
                          -race, -degree)
cDegDists_race2$Date <- as.Date(cDegDists_race2$Date)
cDegDists_race2 <- cDegDists_race2[complete.cases(cDegDists_race2), ]
cMeanDeg_race <- cDegDists_race2 %>% group_by(race, Date) %>% 
  summarise(cMeanDeg = weighted.mean(degree, Number), 
            sd = SD(degree, weights = Number), min = min(degree),
            max = max(degree), .groups = "drop_last")
races <- c("Black", "White", "Other")
max.y <- ceiling(max(cMeanDeg_race$cMeanDeg) * 10) / 10
min.y <- floor(min(cMeanDeg_race$cMeanDeg) * 10) / 10
par(mfrow = c(2,2))
for (i in seq_along(races)) {
    plot(cMeanDeg_race[cMeanDeg_race$race == races[i], ]$Date,
     y = cMeanDeg_race[cMeanDeg_race$race == races[i], ]$cMeanDeg,
     xlab = "Date", ylab = "Mean Degree", 
     main = paste("Mean Deg. over Time -", races[i], sep = " "),
     ylim = c(min.y, max.y)) 
}
plot.new()
max.y <- max(cMeanDeg_race$max)
for (i in seq_along(races)){
  temp <- cMeanDeg_race[cMeanDeg_race$race == races[i], ]
  g <- (ggplot(temp,aes(x=Date)) + 
          geom_boxplot(aes(lower=(cMeanDeg-sd), upper=(cMeanDeg+sd), 
                   middle=cMeanDeg, ymin=min, ymax=max, group = Date), 
               stat="identity") + 
          ggtitle(paste("Mean degree over time -", races[i], sep=" ")) + 
          xlab("Date") + ylab("Degree") + ylim(NA, max.y))
  assign(paste0("r", i), g)
}
grid.arrange(r1, r2, r3, ncol = 2)
remove(cDegDists_race2, temp, r1, r2, r3)
```

#### Mean Degree over Time by Age Group 

```{r}
#Mean degree by age at each time point
cDegDists_age2 <- gather(cDegDists_age, key = "Date", value = "Number", 
                          -age, -degree)
cDegDists_age2$Date <- as.Date(cDegDists_age2$Date)
cDegDists_age2 <- cDegDists_age2[complete.cases(cDegDists_age2), ]
cMeanDeg_age <- cDegDists_age2 %>% group_by(age, Date) %>% 
  summarise(cMeanDeg = weighted.mean(degree, Number), 
            sd = SD(degree, weights = Number), min = min(degree),
            max = max(degree), .groups = "drop_last")
ages <- c("Under 20", "20 - 29", "30 - 39", "40 - 49", "50 - 59", "60+")
max.y <- ceiling(max(cMeanDeg_age$cMeanDeg) * 10) / 10
min.y <- floor(min(cMeanDeg_age$cMeanDeg) * 10) / 10
par(mfrow = c(2,2))
plot.new()
for (i in seq_along(ages)) {
    plot(cMeanDeg_age[cMeanDeg_age$age == ages[i], ]$Date,
     y = cMeanDeg_age[cMeanDeg_age$age == ages[i], ]$cMeanDeg,
     xlab = "Date", ylab = "Mean Degree", 
     main = paste("Mean Deg. over Time - Age", ages[i], 
                  sep = " "), 
     ylim = c(min.y, max.y))
}
plot.new()
max.y <- max(cMeanDeg_age$max)
for (i in seq_along(ages)){
  temp <- cMeanDeg_age[cMeanDeg_age$age == ages[i], ]
  g <- (ggplot(temp,aes(x=Date)) + 
          geom_boxplot(aes(lower=(cMeanDeg-sd), upper=(cMeanDeg+sd), 
                   middle=cMeanDeg, ymin=min, ymax=max, group = Date), 
               stat="identity") + 
          ggtitle(paste("Mean degree over time - Age", ages[i], sep=" ")) +
          xlab("Date") + ylab("Degree") + ylim(NA, max.y))
  assign(paste0("a", i), g)
}
grid.arrange(a1, a2, a3, a4, ncol = 2)
grid.arrange(a5, a6, ncol = 2, heights=unit(0.5, "npc"))
remove(cDegDists_age2, a1, a2, a3, a4, a5, a6, g, temp)
```

#### Mean Degree Averaged Across Selected Timespan (by Attribute)
    
```{r}
#Mean degree by floor averaged across all data
cOverallMeanDeg_floor <- cMeanDeg_floor %>% group_by(floor) %>% 
  summarise(OverallMeanDeg = mean(cMeanDeg), sd = sd(cMeanDeg), 
            min = min(cMeanDeg), max = max(cMeanDeg))
par(mfrow = c(1,1))
ggplot(cOverallMeanDeg_floor,aes(x=floor)) + 
  geom_boxplot(aes(lower=(OverallMeanDeg-sd), upper=(OverallMeanDeg+sd), 
                   middle=OverallMeanDeg, ymin=min, ymax=max, group = floor), 
               stat="identity") + 
  ggtitle(paste0("Mean degree averaged across ", firstDay, " to ", 
             lastDay, " by Floor")) +
  xlab("Floor") + ylab("Mean Degree")

#Mean degree by race averaged across all data 
cOverallMeanDeg_race <- cMeanDeg_race %>% group_by(race) %>% 
  summarise(OverallMeanDeg = mean(cMeanDeg), sd = sd(cMeanDeg), 
            min = min(cMeanDeg), max = max(cMeanDeg))
par(mfrow = c(1,1))
ggplot(cOverallMeanDeg_race,aes(x=race)) + 
  geom_boxplot(aes(lower=(OverallMeanDeg-sd), upper=(OverallMeanDeg+sd), 
                   middle=OverallMeanDeg, ymin=min, ymax=max, group = race), 
               stat="identity") + 
  ggtitle(paste0("Mean degree averaged across ", firstDay, " to ", 
             lastDay, " by Race")) +
  xlab("Race") + ylab("Mean Degree")

#Mean degree by age across all data
cOverallMeanDeg_age <- cMeanDeg_age %>% group_by(age) %>% 
  summarise(OverallMeanDeg = mean(cMeanDeg), sd = sd(cMeanDeg),
            min = min(cMeanDeg), max = max(cMeanDeg))
par(mfrow = c(1,1))
ggplot(cOverallMeanDeg_age,aes(x=age)) + 
  geom_boxplot(aes(lower=(OverallMeanDeg-sd), upper=(OverallMeanDeg+sd), 
                   middle=OverallMeanDeg, ymin=min, ymax=max, group = age), 
               stat="identity") + 
  ggtitle(paste0("Mean degree averaged across ", firstDay, " to ", 
             lastDay, " by Age")) +
  xlab("Age") + ylab("Mean Degree")

#Remove unneeded variables
remove(i, j, races, floors, ages)
```
