---
title: "Step0-InitialProcessing"
author: "Karina Wallrafen-Sam"
date: "4/1/2022"
output: html_document
---

```{r, include = FALSE}
library(readxl)
library(tidyr)
library(dplyr)

#Load all excel files from the data/input/FJC folder into the files list
filenames <- list.files("../data/input/FJC", pattern="*.xlsx", full.names=TRUE)
files <- lapply(filenames, read_excel)
#Name the sub-lists (one for each file) based on the file names
names(files) <- substr(gsub(" ", "_",
                            gsub("\\(", "",
                                 gsub("\\)", "", filenames))), 36, 43)

#Basic data cleaning
for (i in seq_along(files)){
  #Keep only the SO Number, DOB, Gender, Race, and Cell/Cell Location columns
  files[[i]] <- files[[i]][ , grepl( "So|SO|DOB|Gender|Race|Cell" ,
                                     names( files[[i]] ) ) ]
  #Check that each sub-list has the right number of columns
  if (ncol(files[[i]]) != 5){
    stop("Wrong number of columns selected")
  }
  #Add a column for the date of data collection
  files[[i]]$Date <- names(files)[i]
  #Standardize column names and date formats
  colnames(files[[i]])[grepl('So|SO',colnames(files[[i]]))] <- 'SoNum'
  colnames(files[[i]])[grepl('Cell',colnames(files[[i]]))] <- 'Location'
  files[[i]]$Date <- as.Date(files[[i]]$Date, "%Y%m%d")
  files[[i]]$DOB <- as.Date(files[[i]]$DOB)
}

#Concatenate the sub-lists into one long data frame
all_data = do.call(rbind, files)
remove(files, filenames, i)

#Check for missing values
sapply(all_data, function(x) sum(is.na(x)))
#Check for uniqueness of SO Numbers
check_so <- all_data %>% group_by(SoNum) %>%
  summarise(DOBs = n_distinct(DOB), Genders = n_distinct(Gender),
            Races = n_distinct(Race))
sapply(check_so, function(x) sum(x > 1))
remove(check_so)
#Select most recent DOB/Race and initial Gender for those with multiple
all_data <- all_data %>% group_by(SoNum) %>%
  mutate(DOB = last(DOB), Race = last(Race), Gender = first(Gender)) %>% ungroup
#Check for reasonableness of data
summary(all_data$DOB)
table(all_data$Gender)
table(all_data$Race)
#Check for data gaps
timeGaps <- all_data[with(all_data, order(SoNum, Date)), ]
timeGaps <- timeGaps %>% group_by(Date) %>% mutate(Day = cur_group_id()) %>%
  ungroup()
timeGaps <- which(timeGaps$SoNum==lag(timeGaps$SoNum) &
                    timeGaps$Day != (lag(timeGaps$Day) + 1))

#Subset only to the time frame of interest
all_data <- all_data[all_data$Date >= firstDay & all_data$Date <= lastDay, ]

#For now: Separate out women and men with special locations
data_m <- subset(all_data, Gender == "M")
data_f <- subset(all_data, Gender == "F")
data_m$Location <- gsub(" - Male", "", data_m$Location)
data_f$Location <- gsub(" - Female", "", data_f$Location)
if (nrow(all_data) != (nrow(data_f) + nrow(data_m))){
  warning("Check for missing values in the Gender column")}
m_stdLoc <- data_m[!grepl("[A-M]|[O-R]|[T-Z]|[a-z]", data_m$Location), ]
m_specialLoc <- data_m[grepl("[A-M]|[O-R]|[T-Z]|[a-z]", data_m$Location), ]
remove(data_m)

#Check if any SO Numbers got split across data frames
std_split <- subset(m_stdLoc, m_stdLoc$SoNum %in% m_specialLoc$SoNum)
std_split <- std_split[!duplicated(std_split$SoNum),]

#Continuing only with men with standard locations...

#Calculate how many times each person appears in the data and in how many places
ids <- m_stdLoc %>% group_by(SoNum) %>%
  summarise(DaysOfData = n(), FirstDate = min(Date), LastDate = max(Date),
            NumLocs = n_distinct(Location), DOB = last(DOB),
            Gender = first(Gender), Race = last(Race))
ids$id <- 1:nrow(ids)
ids$Duration <- ids$LastDate - ids$FirstDate + 1
ids$InitialAge <- as.integer((ids$FirstDate - ids$DOB)/365.25)

#Split the cell location column into floor, tower, block, and cell
m_stdLoc <- separate(data = m_stdLoc, col = 5,
                               into = c("Floor", "Tower", "Block", "Cell"),
                               sep = c(1, 2, 3))

#Contacts by Block and Cell
contacts <- m_stdLoc %>% group_by(Date, Floor, Tower, Block) %>%
  mutate(BlockContacts = n_distinct(SoNum)) %>% ungroup()
contacts <- contacts %>% group_by(Date, Floor, Tower, Block, Cell) %>%
  mutate(CellContacts = n_distinct(SoNum)) %>% ungroup()
contacts$BlockContacts <- contacts$BlockContacts - 1
contacts$CellContacts <- contacts$CellContacts - 1
```

```{r}
#Demographic breakdown - Overall
ids2 <- ids
ids2$InitialAge <- cut(ids2$InitialAge, breaks=c(0, 20, 30, 40, 50, 60, 100), 
                       right = FALSE, labels = c("Under 20", "20 - 29", 
                                                 "30 - 39", "40 - 49", 
                                                 "50 - 59", "60+"))
ids2[ids2$Race != "White" & ids2$Race != "Black", ]$Race <- "Other"
ids2 <- rename(ids2,c('Age'='InitialAge'))

# knitr::kable(table(ids2$Gender), 
#              caption = "Total # of Residents by Gender", 
#              col.names = c("Gender", "Freq"))
# knitr::kable(table(ids2$Race), 
#              caption = "Total # of Residents by Race",
#              col.names = c("Race", "Freq"))
# knitr::kable(table(ids2$Age), 
#              caption = "Total # of Residents by Age",
#              col.names = c("Age Group", "Freq"))

#Demographic breakdown - First Day
ids3 <- ids2[ids2$FirstDate == firstDay, ]
ids3 <- merge(ids3, m_stdLoc[m_stdLoc$Date == firstDay, c("SoNum", "Floor")], 
              by = "SoNum")
knitr::kable(table(ids3$Gender), 
             caption = "Initial # of Residents by Gender", 
             col.names = c("Gender", "Freq"))
knitr::kable(table(ids3$Race),
             caption = "Initial # of Residents by Race",
             col.names = c("Race", "Freq"))
knitr::kable(table(ids3$Age),
             caption = "Initial # of Residents by Age",
             col.names = c("Age Group", "Freq"))
knitr::kable(table(ids3$Floor),
             caption = "Initial # of Residents by Floor",
             col.names = c("Floor", "Freq"))
# knitr::kable((ids3 %>% count(Floor, Gender, Race, Age)), 
#              caption = "Initial # of Residents by Floor, Gender, Race, and Age")

#Demographic breakdown - Last Day
ids4 <- ids2[ids2$LastDate == lastDay, ]
ids4 <- merge(ids4, m_stdLoc[m_stdLoc$Date == lastDay, c("SoNum", "Floor")], 
              by = "SoNum")
knitr::kable(table(ids4$Gender), 
             caption = "Final # of Residents by Gender",
             col.names = c("Gender", "Freq"))
knitr::kable(table(ids4$Race),
             caption = "Final # of Residents by Race",
             col.names = c("Race", "Freq"))
knitr::kable(table(ids4$Age),
             caption = "Final # of Residents by Age",
             col.names = c("Age Group", "Freq"))
knitr::kable(table(ids4$Floor),
             caption = "Final # of Residents by Floor",
             col.names = c("Floor", "Freq"))
# knitr::kable((ids4 %>% count(Floor, Gender, Race, Age)), 
#              caption = "Final # of Residents by Floor, Gender, Race, and Age")

remove(ids2, ids3, ids4)
```

